// <auto-generated />
using System;
using GeoSensePlus.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoSensePlus.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250718132222_5")]
    partial class _5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.AlarmEvent.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Severity")
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("alarm", "alarm_event");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.AlarmEvent.EventRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("event_record", "alarm_event");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("FloorPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("floor_plan_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanId");

                    b.ToTable("area", "location");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("building", "location");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("floor", "location");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.FloorPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FileLocation")
                        .HasColumnType("text")
                        .HasColumnName("file_location");

                    b.Property<int?>("FloorId")
                        .HasColumnType("integer")
                        .HasColumnName("floor_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("FloorId");

                    b.ToTable("floor_plan", "location");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("site", "location");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Map.Geofence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Shape")
                        .HasColumnType("text")
                        .HasColumnName("shape");

                    b.HasKey("Id");

                    b.ToTable("geofence", "map");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Map.Marker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AxisX")
                        .HasColumnType("double precision")
                        .HasColumnName("axis_x");

                    b.Property<double>("AxisY")
                        .HasColumnType("double precision")
                        .HasColumnName("axis_y");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("FloorPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("floor_plan_id");

                    b.Property<bool>("IsPoi")
                        .HasColumnType("boolean")
                        .HasColumnName("is_poi");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanId");

                    b.ToTable("marker", "map");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int?>("ValueId")
                        .HasColumnType("integer")
                        .HasColumnName("value_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ValueId");

                    b.HasIndex("Name", "ParentId")
                        .IsUnique();

                    b.ToTable("point", "messaging");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.PointGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Name", "ParentId")
                        .IsUnique();

                    b.ToTable("point_group", "messaging");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PointId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PointId");

                    b.ToTable("topic", "messaging");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("boolean_value");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<float?>("FloatValue")
                        .HasColumnType("real")
                        .HasColumnName("float_value");

                    b.Property<int?>("IntegerValue")
                        .HasColumnType("integer")
                        .HasColumnName("integer_value");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueString")
                        .HasColumnType("text")
                        .HasColumnName("value_string");

                    b.HasKey("Id");

                    b.ToTable("value", "messaging");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Sensing.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Labels")
                        .HasColumnType("text")
                        .HasColumnName("labels");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("measure", "sensing");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Sensing.Sensor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Labels")
                        .HasColumnType("text")
                        .HasColumnName("labels");

                    b.Property<int?>("MeasureId")
                        .HasColumnType("integer")
                        .HasColumnName("measure_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("MeasureId");

                    b.ToTable("sensor", "sensing");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.CellAnchor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("area_id");

                    b.Property<int?>("CellHubId")
                        .HasColumnType("integer")
                        .HasColumnName("cell_hub_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AreaId")
                        .IsUnique();

                    b.HasIndex("CellHubId");

                    b.ToTable("cell_anchor", "positioning");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.CellHub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("cell_hub", "positioning");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.CellTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CellAnchorId")
                        .HasColumnType("integer");

                    b.Property<int?>("CellHubId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CellAnchorId");

                    b.HasIndex("CellHubId");

                    b.HasIndex("TargetId");

                    b.ToTable("cell_tag", "positioning");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.GpsTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Altitude")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.ToTable("gps_tag", "positioning");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.Target", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("target", "positioning");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.UwbAnchor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AxisX")
                        .HasColumnType("double precision")
                        .HasColumnName("axis_x");

                    b.Property<double>("AxisY")
                        .HasColumnType("double precision")
                        .HasColumnName("axis_y");

                    b.Property<double>("AxisZ")
                        .HasColumnType("double precision")
                        .HasColumnName("axis_z");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("FloorPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("floor_plan_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanId");

                    b.HasIndex("SiteId");

                    b.ToTable("uwb_anchor", "positioning");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.UwbTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AxisX")
                        .HasColumnType("double precision")
                        .HasColumnName("axis_x");

                    b.Property<double>("AxisY")
                        .HasColumnType("double precision")
                        .HasColumnName("axis_y");

                    b.Property<double>("AxisZ")
                        .HasColumnType("double precision")
                        .HasColumnName("axis_z");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.ToTable("uwb_tag", "positioning");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Area", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.FloorPlan", "Floorplan")
                        .WithMany("Areas")
                        .HasForeignKey("FloorPlanId");

                    b.Navigation("Floorplan");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Building", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.Site", "Site")
                        .WithMany("Buildings")
                        .HasForeignKey("SiteId");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Floor", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId");

                    b.Navigation("Building");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.FloorPlan", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.Building", null)
                        .WithMany("FloorPlans")
                        .HasForeignKey("BuildingId");

                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.Floor", "Floor")
                        .WithMany("Floorplans")
                        .HasForeignKey("FloorId");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Map.Marker", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.FloorPlan", "Floorplan")
                        .WithMany()
                        .HasForeignKey("FloorPlanId");

                    b.Navigation("Floorplan");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.Point", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Messaging.PointGroup", "Parent")
                        .WithMany("Points")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Messaging.Value", "Value")
                        .WithMany("Points")
                        .HasForeignKey("ValueId");

                    b.Navigation("Parent");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.PointGroup", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Messaging.PointGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.Topic", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Messaging.Point", null)
                        .WithMany("Topics")
                        .HasForeignKey("PointId");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Sensing.Sensor", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Sensing.Measure", "Measure")
                        .WithMany("Sensors")
                        .HasForeignKey("MeasureId");

                    b.Navigation("Area");

                    b.Navigation("Measure");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.CellAnchor", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.Area", "Area")
                        .WithOne("CellAnchor")
                        .HasForeignKey("GeoSensePlus.Data.DatabaseModels.Tracking.CellAnchor", "AreaId");

                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Tracking.CellHub", "CellHub")
                        .WithMany("CellAnchors")
                        .HasForeignKey("CellHubId");

                    b.Navigation("Area");

                    b.Navigation("CellHub");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.CellTag", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Tracking.CellAnchor", null)
                        .WithMany("CellTags")
                        .HasForeignKey("CellAnchorId");

                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Tracking.CellHub", null)
                        .WithMany("CellTags")
                        .HasForeignKey("CellHubId");

                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Tracking.Target", "Target")
                        .WithMany("CellTags")
                        .HasForeignKey("TargetId");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.GpsTag", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Tracking.Target", "Target")
                        .WithMany("GpsTags")
                        .HasForeignKey("TargetId");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.UwbAnchor", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.FloorPlan", "Floorplan")
                        .WithMany()
                        .HasForeignKey("FloorPlanId");

                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Location.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("Floorplan");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.UwbTag", b =>
                {
                    b.HasOne("GeoSensePlus.Data.DatabaseModels.Tracking.Target", "Target")
                        .WithMany("UwbTags")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Area", b =>
                {
                    b.Navigation("CellAnchor");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Building", b =>
                {
                    b.Navigation("FloorPlans");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Floor", b =>
                {
                    b.Navigation("Floorplans");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.FloorPlan", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Location.Site", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.Point", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.PointGroup", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Points");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Messaging.Value", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Sensing.Measure", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.CellAnchor", b =>
                {
                    b.Navigation("CellTags");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.CellHub", b =>
                {
                    b.Navigation("CellAnchors");

                    b.Navigation("CellTags");
                });

            modelBuilder.Entity("GeoSensePlus.Data.DatabaseModels.Tracking.Target", b =>
                {
                    b.Navigation("CellTags");

                    b.Navigation("GpsTags");

                    b.Navigation("UwbTags");
                });
#pragma warning restore 612, 618
        }
    }
}
